# control.yaml
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
  
diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: 'wl_link'  # Name of the left wheel joint
  right_wheel: 'wr_link'  # Name of the right wheel joint
  publish_rate: 50.0
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.03, 0.03, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.03, 0.03, 0.03]

  # Wheel separation and diameter, these values need to be set according to your robot's physical specs
  wheel_separation: 0.2
  wheel_radius: 0.05

  # Command timeout and base frame id
  cmd_vel_timeout: 0.
