DWAPlannerROS:
  # Parámetros de configuración del robot
  acc_lim_x: 1.0  # Reducido para suavizar las aceleraciones lineales
  acc_lim_y: 0.0
  acc_lim_theta: 1.5  # Reducido para suavizar las aceleraciones angulares
  max_vel_x: 0.3  # Reducido para un movimiento más controlado
  min_vel_x: 0.1  # Permite que el robot se detenga completamente antes de girar
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_vel_trans: 0.4  # Reducido para mejorar el control de la velocidad de translación
  min_vel_trans: 0.1
  max_vel_theta: 1.5  # Reducido para permitir giros controlados
  min_vel_theta: 0.1  # Reducido para permitir giros más lentos y precisos

  # Parámetros de tolerancia del objetivo
  xy_goal_tolerance: 0.15  # Mantenido para flexibilidad
  yaw_goal_tolerance: 0.2  # Mantenido para permitir un margen de error en giros
  latch_xy_goal_tolerance: false  # Mantenido deshabilitado para mayor precisión

  # Parámetros de simulación hacia adelante
  sim_time: 2.0  # Reducido para responder más rápidamente y procesar menos trayectorias
  sim_granularity: 0.025
  min_in_place_vel_theta: 0.2  # Reducido para permitir giros controlados en el lugar
  acc_lim_trans: 1.0  # Reducido para suavizar las aceleraciones de translación
  vx_samples: 20  # Reducido para disminuir la carga computacional
  vtheta_samples: 20  # Reducido para disminuir la carga computacional
  controller_frequency: 5.0  # Ajustado según el nuevo ritmo de actualización
  
  # Parámetros de puntuación de trayectorias
  path_distance_bias: 50.0  # Aumentado para enfatizar seguir el camino planificado
  goal_distance_bias: 10.0  # Reducido para desalentar el enfoque directo al objetivo
  occdist_scale: 0.01  # Reducido para ajustar la sensibilidad a los obstáculos
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  publish_cost_grid: false

  # Parámetros de oscilación
  oscillation_reset_dist: 0.05

  # Parámetros de plan global
  prune_plan: true
