obstacle_range: 1.0
raytrace_range: 0.5
robot_radius: 0.12
obstacles_layer: 
  observation_sources: scan
  scan: {sensor_frame: base_scan, data_type: LaserScan, topic: scan, marking: true, clearing: true, min_obstacle_height: -2.0, max_obstacle_height: 2.0, obstacle_range: 2.5, raytrace_range: 3.0}

#In charge of providing the static map to the costmaps that require it (global)
static:
  #Can't comment out eventhough it has the default value because if not it will
  #generate cannot marhsal None unless allow_none is enabled
  map_topic: map #Defult: map