DWAPlannerROS:
  # Parámetros de configuración del robot
  acc_lim_x: 2.5  # Incrementado para permitir una aceleración más rápida
  acc_lim_y: 0.0
  acc_lim_theta: 4.5  # Ajustado para permitir aceleraciones angulares rápidas pero controladas
  max_vel_x: 0.3  # Moderadamente reducido para un movimiento controlado
  min_vel_x: 0.0  # Permite que el robot se detenga completamente antes de girar
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_vel_trans: 0.55
  min_vel_trans: 0.1
  max_vel_theta: 1.5  # Aumentado para permitir giros más rápidos pero controlados
  min_vel_theta: 0.3  # Aumentado para permitir giros más controlados en el lugar

  # Parámetros de tolerancia del objetivo
  xy_goal_tolerance: 0.15  # Aumentado ligeramente para mayor flexibilidad
  yaw_goal_tolerance: 0.2  # Aumentado para permitir un margen de error mayor en giros
  latch_xy_goal_tolerance: false  # Deshabilitado para mayor precisión

  # Parámetros de simulación hacia adelante
  sim_time: 1.7  # Mantener bajo para mayor respuesta
  sim_granularity: 0.025
  min_in_place_vel_theta: 0.4  # Moderadamente reducido para giros más controlados en el lugar
  acc_lim_trans: 2.0  # Incrementado para permitir una aceleración más rápida
  vx_samples: 40  # Incrementado para más opciones de trayectorias lineales
  vtheta_samples: 40  # Mantener alto para mayor variedad de giros
  controller_frequency: 20.0
  
  # Parámetros de puntuación de trayectorias
  path_distance_bias: 24.0
  goal_distance_bias: 32.0
  occdist_scale: 0.01
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2
  publish_cost_grid: false

  # Parámetros de oscilación
  oscillation_reset_dist: 0.05

  # Parámetros de plan global
  prune_plan: true
