local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 20.0
  publish_frequency: 2.0
  width: 5.0
  height: 5.0
  resolution: 0.01
  rolling_window: true

  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflater_layer, type: "costmap_2d::InflationLayer"}

  obstacles_layer:
    observation_sources: laser_scan
    laser_scan: {sensor_frame: laser_frame, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

  inflater_layer:
    inflation_radius: 0.15  # Moderado para asegurar una distancia adecuada a los obstáculos
    cost_scaling_factor: 7.0
