local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  width: 0.5
  height: 0.5
  resolution: 0.05
  rolling_window: true
  #In charge of inflating (blue color in RVIZ) each cell with an obstacle
  inflater_layer:
  #inflation_radius: 0.30
  #Increased for better detecting obstacles
    inflation_radius: 0.2 #Default: 0.55
  #Scaling factor to apply cost values during inflation
  #cost_scaling_factor: 10.0 #Default: 10.0

  
  
  plugins:
    - {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflater_layer, type: "costmap_2d::InflationLayer"}