local_costmap:
  global_frame: map  # Cambiado de 'map' a 'odom' para que sea adecuado para local_costmap
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 5.0
  width: 10.0
  height: 10.0
  resolution: 0.05
  rolling_window: true
  static_map: false
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  inflation_layer:
    inflation_radius: 0.3  # Disminuido desde un valor mayor para reducir el tama침o de la inflaci칩n
    cost_scaling_factor: 10.0  # Ajusta este valor si necesitas modificar c칩mo decrece el costo con la distancia desde un obst치culo
