DWAPlannerROS:
  acc_lim_x: 0.3
  acc_lim_y: 0.0
  acc_lim_theta: 1.5

  max_vel_x: 0.25
  min_vel_x: 0.1
  max_vel_y: 0.0
  min_vel_y: 0.0

  max_vel_trans: 0.25
  min_vel_trans: 0.05

  max_vel_theta: 2.5
  min_vel_theta: -2.5

  xy_goal_tolerance: 0.02
  yaw_goal_tolerance: 0.01
  latch_xy_goal_tolerance: false

  sim_time: 2.5
  sim_granularity: 0.025
  min_in_place_vel_theta: 0.05
  acc_lim_trans: 0.7
  vx_samples: 10
  vtheta_samples: 60

  controller_frequency: 3.0

  path_distance_bias: 70.0
  goal_distance_bias: 20.0
  occdist_scale: 0.01
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

  publish_cost_grid: false

  oscillation_reset_dist: 0.05

  prune_plan: true

  rot_stopped_vel: 0.1
  trans_stopped_vel: 0.1
